### ISSUE TITLE
Add 'formal' version with all the solvers

### ISSUE THREAD

**Issue by eine** [ghdl/docker#14]
Ref https://gist.github.com/tmeissner/e1d7b3f9adedfa87473dc908a4f11398

**Comment by 1138-4EB** [comment]
> [@tmeissner]
> maybe it would be better to install the solversin /usr/local/bin
> with only one solver, iot is okay to add it to the PATH variable, but not when installing many solvers

> [@1138-4EB]
> That's fair. I don't remember now why I avoided installing in /usr/local. I think that I didn't use prefix and DESTDIR properly, so there was a mismatch between hardcoded paths and installation location. I will revisit it to ensure that all the solvers are available in the PATH.

**Comment by eine** [comment]
Ref [tmeissner/Dockerfiles](https://github.com/tmeissner/Dockerfiles)

**Comment by eine** [comment]
Thanks to @tmeissner's contributions, multiple images with several solvers are available in [https://github.com/hdl/containers](hdl/containers). See https://hdl.github.io/containers/#_tools_and_images
