### ISSUE TITLE
Fix permissions of /opt/* directories

### ISSUE THREAD

**Issue by eine** [ghdl/docker#16]
> [@tmeissner]
> I've tested the ghdl/synth:formal Docker image. In the image, the tool directories under /opt/ are only readable by root. So, if I run the image as non-root user, I can't use the tools as intended
>
> I can live with installing in /opt, a simple change of permissions would be sufficient for me

> [@1138-4EB]
> 755 is ok?

> [@tmeissner]
> I think so
> The subdirectories of ghdl and the other tools have correct permissions
> So, only the 3 directories ghdl, yosys & z3 have to changed to 755

> [@1138-4EB]
> That makes sense. The 'wrong' command is just the mkdir before running tar. The content extracted by tar is correct.
>
> Oh. I'm not using tar anymore. I forgot that. Neither mkdir. The directory is implicitly created by COPY in the dockerfiles:
>
> - https://github.com/tgingold/ghdlsynth-beta/blob/master/travis.sh#L43
> - https://github.com/1138-4EB/ghdl-docker/blob/master/dockerfiles/cache_formal#L30-L31

Although it was reported for `ghdl/synth:formal`, other images are likely to be affected too. At least `ghdl/synth:beta` and `ghdl/synth:latest`.

**Comment by eine** [comment]
@tmeissner, this should be fixed now. I changed all the images so that tools are installed in `/usr/local`. Would you mind testing?

**Comment by tmeissner** [comment]
The tools are found in the `ghdl/synth:formal` Image. Another problem is, that none of my test designs work anymore because of GHDL regressions I assume :-(

**Comment by eine** [comment]
Oh, that's unfortunate. The tests you contributed to ghdlsynth-beta seem to be passing. Hence, it must be some more advanced feature in your tests. Nevertheless, in this issue I was concerned about permissions issues when you used the images as a non-root user in your scripts. Since it seems to be fixed, I'll close it. Anyway, do not hesitate to ping again, since I might have forgotten to fix some other image...
