### ISSUE TITLE
Pulling from Docker Hub fails.

### ISSUE THREAD

**Issue by m-kru** [ghdl/docker#19]
```
docker pull ghdl/ghdl

Using default tag: latest
Error response from daemon: manifest for ghdl/ghdl:latest not found: manifest unknown: manifest unknown
```

**Comment by 1138-4EB** [comment]
Please, see https://github.com/ghdl/docker/issues/15#issuecomment-527054766:

> There is no 'default' (`ghdl/ghdl:latest`) image; that's why docker pull ghdl/ghdl fails. It is unfortunate that dockerhub suggest the command without ensuring that a valid tag exists.
