### ISSUE TITLE
Docker Resource Consumption Updates 

### ISSUE THREAD

**Issue by eine** [ghdl/docker#30]
https://www.docker.com/pricing/resource-consumption-updates

> **What are the rate limits for pulling Docker images from the Docker Hub Registry?**
> Rate limits for Docker image pulls are based on the account type of the user requesting the image - not the account type of the image’s owner. These are defined on the [pricing](https://www.docker.com/pricing) page.
>
> The highest entitlement a user has, based on their personal account and any orgs they belong to, will be used. Unauthenticated pull requests are “anonymous” and will be rate limited based on IP address rather than user ID. For more information on authenticating image pulls, please see this [docs page](https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests).

> **How is a pull request defined for purposes of rate limiting?**
> A pull request is up to two GET requests to the registry URL path ‘/v2/*/manifests/*’.
> 
> This accounts for the fact that pull requests for multi-arch images require a manifest list to be downloaded followed by the actual image manifest for the required architecture. HEAD requests are not counted.
> 
> Note that all pull requests, including ones for images you already have, are counted by this method. This is the trade-off for not counting individual layers.

> **Are anonymous (unauthenticated) pulls rate-limited based on IP address?**
> Yes. Pull rates are limited based on individual IP address (e.g., for anonymous users: 100 pulls per 6 hours per IP address).

> **What about CI systems where pulls will be anonymous?**
> We recognize there are some circumstances where many pulls will be made that can not be authenticated. For example, cloud CI providers may host builds based on PRs to open source projects. The project owners may be unable to securely use their project’s Docker Hub credentials to authenticate pulls in this scenario, and the scale of these providers would likely trigger the anonymous rate limits. We will unblock these scenarios as necessary and continue iterating on our rate limiting mechanisms to improve the experience, in cooperation with these providers. Please reach out to support@docker.com if you are encountering issues.

> **Will Docker offer dedicated plans for open source projects?**
> Yes, as part of Docker’s commitment to the open source community, we will be announcing the availability of new open source plans. To apply for an open source plan, complete our application at: https://www.docker.com/community/open-source-application.

For now, we should be safe. However, we might want to apply for an open source plan in the future.

/cc @tmeissner

**Comment by umarcor** [comment]
Closing, since we did not run into issues during the last year.
