### ISSUE TITLE
Some build actions are not running due to inactivity

### ISSUE THREAD

**Issue by djmatt** [ghdl/docker#49]
It looks like some of the build actions, that are schedule based, are not running due to inactivity in this repository.  

As a result, some of the docker images on docker hub are now several months out of date.

**Comment by tgingold** [comment]
I have just restarted it.  Thanks!

**Comment by djmatt** [comment]
Unfortunately, I don't think this issue is resolved.  I see that the base workflow was started manually, however most of the rest of the workflows have not run in several months (bookworm, vunit, co-sim, etc.) due to being scheduled workflows.  I believe that GitHub disabled the scheduled workflows due to inactivity in the code repository.

**Comment by tgingold** [comment]
I have regenerated all the images.
